# Generated by Django 2.0.3 on 2018-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20180402_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winedata',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
